# Generated by Django 4.1.9 on 2024-11-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email_info",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
