# Generated by Django 4.1.9 on 2024-11-16 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0002_email_info_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="email_info",
            name="flipID",
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="email_info",
            name="phone_number",
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="email_info",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
