# Generated by Django 4.1.9 on 2024-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0003_email_info_flipid_email_info_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email_info",
            name="order_id",
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
