# Generated by Django 4.1.9 on 2024-11-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0004_email_info_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email_info",
            name="flipID",
        ),
    ]
